config/routes.rb
Rails.application.routes.draw do

  root 'login#login'

  get 'home' => 'application#home'

  get 'login' => 'login#login'

  post 'login' => 'login#authenticate'

  get 'signup' => 'login#signup'

  post 'signup' => 'login#create_user'

  get 'projects' => 'project#index'

  get 'projects/new' => 'project#new'

  post 'projects' => 'project#create'

  get 'projects/:id' => 'project#show'

  post 'projects/:id/pledge' => 'project#pledge'

  post 'projects/:id/rating' => 'project#rating'

  post 'projects/:id/comment' => 'project#comment', :as => 'project_comments'

  post 'projects/:id/like' => 'project#like'

  get 'users/:id' => 'user#show'

  get 'users/:id/projects' => 'user#projects'

  get 'users/:id/followers' => 'user#followers'

  get 'users/:id/following' => 'user#following'

  post 'users/:id/profile/:profile_type/follow' => 'user#follow'

  post 'users/:id/profile/:profile_type/unfollow' => 'user#unfollow'

  post 'users/:id/following/follow' => 'user#follow'

  get 'users/:id/account' => 'user#account'

  post 'users/:id/account' => 'user#reset_password', as: 'password_reset'

  get 'users/:id/profile' => 'user#profile'

  post 'users/:id/profile' => 'user#update_profile', as: 'profile_update'

  get 'users/:id/recommendations' => 'user#recommendations'

  get 'users/:id/credit_cards' => 'user#credit_cards'

  get 'users/:id/profile/about' => 'user#about'

  get 'users/:id/profile/backed' => 'user#backed'

  get 'users/:id/profile/comments' => 'user#comments'

  post 'credit_cards' => 'credit_card#new'

  delete 'credit_cards/:cc_number' => 'credit_card#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  self.table_name = 'users'
  self.primary_key = 'id'

  has_attached_file :profile_image,
                    styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :profile_image, content_type: /\Aimage\/.*\z/
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :deep_munge_empty_strings, only: [:update_profile]

  def show
    binding.pry
  end

  def new
  end

  def index
  end

  def account
    @user = ActiveRecord::Base.connection.execute("SELECT * FROM users where id=#{params[:id].to_i}").first
  end

  def reset_password
    current_password = ActiveRecord::Base.connection.execute("SELECT password FROM users WHERE id=#{params[:id].to_i}").first['password']

    if current_password != params['current_password']
      redirect_to "/users/#{params[:id]}/account", alert: "PASSWORD IS INCORRECT. SYSTEM WILL SELF DESTRUCT IN 10 mins"
      return
    end

    if params[:password] == params[:confirm_password] && params[:password].length != 0
      ActiveRecord::Base.connection.execute("
        UPDATE users
        SET password='#{params['password']}',
            email='#{params['email']}'
        WHERE id=#{params[:id].to_i}
      ")
      redirect_to "/users/#{params[:id]}/account", notice: "PASSWORD RESET SUCCESSFULLY!"
      return
    end
    redirect_to "/users/#{params[:id]}/account"
  end

  def followers
    @followers = ActiveRecord::Base.connection.execute("SELECT * FROM followers INNER JOIN users ON followers.follower_id = users.id WHERE followers.following_id=#{params[:id].to_i}").to_a
    @followers.each do |follower|
      ar_follower = User.find(follower['id'].to_i)
      unless ar_follower.profile_image_file_name.nil?
        follower['profile_image'] = ar_follower.profile_image.url
      end
    end


    @following = ActiveRecord::Base.connection.execute("SELECT * FROM followers INNER JOIN users ON followers.following_id = users.id WHERE followers.follower_id=#{params[:id].to_i}").to_a
    @backed = ActiveRecord::Base.connection.execute("SELECT DISTINCT(project_id) FROM pledges WHERE user_id=#{params[:id].to_i}")
  end

  def following
    @followers = ActiveRecord::Base.connection.execute("SELECT * FROM followers INNER JOIN users ON followers.follower_id = users.id WHERE followers.following_id=#{params[:id].to_i}")
    @following = ActiveRecord::Base.connection.execute("SELECT * FROM followers INNER JOIN users ON followers.following_id = users.id WHERE followers.follower_id=#{params[:id].to_i}").to_a
    @following.each do |following|
      ar_following = User.find(following['id'].to_i)
      unless ar_following.profile_image_file_name.nil?
        following['profile_image'] = ar_following.profile_image.url
      end
    end
    @backed = ActiveRecord::Base.connection.execute("SELECT DISTINCT(project_id) FROM pledges WHERE user_id=#{params[:id].to_i}")
  end

  def profile
    @user = User.find(params[:id])
  end

  def update_profile
    ActiveRecord::Base.connection.execute("
    UPDATE users
    SET first_name=#{ActiveRecord::Base.sanitize(params['first_name'])},
        last_name=#{ActiveRecord::Base.sanitize(params['last_name'])},
        username=#{ActiveRecord::Base.sanitize(params['username'])},
        profile_image_url=#{ActiveRecord::Base.sanitize(params['profile_image_url'])},
        biography=#{ActiveRecord::Base.sanitize(params['biography'])},
        address=#{ActiveRecord::Base.sanitize(params['address'])},
        state=#{ActiveRecord::Base.sanitize(params['state'])},
        country=#{ActiveRecord::Base.sanitize(params['country'])},
        pincode=#{ActiveRecord::Base.sanitize(params['pincode'])}
    WHERE id=#{params[:id].to_i}
    ")

    if params[:profile_image]
      user = User.find(params[:id].to_i)
      user.profile_image = params[:profile_image]
      user.save!
    end

    redirect_to "/users/#{params[:id]}/profile"
  end

  def projects
    user_projects_sql = "SELECT projects.id, projects.title, projects.description, projects.maximum_fund, projects.search_thumbnail_small, projects.search_thumbnail_large, projects.video_url, users.first_name, users.last_name, projects.location, EXTRACT(EPOCH FROM (projects.end_date - CURRENT_TIMESTAMP))/(60*60*24) AS days_left , pledge_sums.pledge_sum
                FROM projects
                FULL OUTER JOIN (
                SELECT projects.id AS id, SUM(pledges.amount) AS pledge_sum
                FROM projects
                INNER JOIN pledges
                ON projects.id = pledges.project_id
                GROUP BY projects.id
                ) AS pledge_sums
                ON projects.id = pledge_sums.id
                INNER JOIN users
                ON users.id = projects.posted_by
                WHERE projects.posted_by=#{params[:id]}"

    projects = ActiveRecord::Base.connection.execute(user_projects_sql).to_a
    projects.each do |project|
      ar_project = Project.find(project['id'].to_i)
      unless ar_project.project_image_file_name.nil?
        project['project_image_url'] = ar_project.project_image.url
      end
    end

    @projects = [[], [], [], [], [], [], []]

    projects.each_with_index do |project, index|
      @projects[index/4] << project
    end
  end

  def recommendations
    recommend_sql = "SELECT projects.id, projects.title, projects.description, projects.maximum_fund, projects.search_thumbnail_small, projects.search_thumbnail_large, projects.video_url, users.first_name, users.last_name, projects.location, EXTRACT(EPOCH FROM (projects.end_date - CURRENT_TIMESTAMP))/(60*60*24) AS days_left , CASE WHEN pledge_sums.pledge_sum is null THEN 0 ELSE pledge_sums.pledge_sum END
                FROM projects
                FULL OUTER JOIN (
                SELECT projects.id AS id, SUM(pledges.amount) AS pledge_sum
                FROM projects
                INNER JOIN pledges
                ON projects.id = pledges.project_id
                GROUP BY projects.id
                ) AS pledge_sums
                ON projects.id = pledge_sums.id
                INNER JOIN users
                ON users.id = projects.posted_by
                WHERE projects.id IN
                (
                  SELECT project_id
                  FROM (
                          SELECT project_id, COUNT(*) AS no_of_views
                          FROM events
                          WHERE user_id=#{current_user['id']}
                          AND type='project_views'
                          GROUP BY project_id ORDER BY no_of_views DESC
                        ) AS A
                ) ORDER BY random() limit 6"

    @recommendations = ActiveRecord::Base.connection.execute(recommend_sql).to_a

    @recommendations.each do |project|
      ar_project = Project.find(project['id'].to_i)
      unless ar_project.project_image_file_name.nil?
        project['project_image_url'] = ar_project.project_image.url
      end
    end
  end

  def about
    ActiveRecord::Base.connection.execute("INSERT INTO events (user_id, profile_id, type, created_at, updated_at) VALUES (#{current_user['id']}, #{params[:id]}, 'profile_views', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)")
    @user = User.find(params[:id].to_i)
    @projects = ActiveRecord::Base.connection.execute("SELECT * FROM projects WHERE id IN (SELECT projects.id FROM projects INNER JOIN pledges ON projects.id = pledges.project_id WHERE pledges.user_id=#{params[:id].to_i})")
    @comments = ActiveRecord::Base.connection.execute("SELECT projects.title, reviews.comment, reviews.created_at FROM reviews INNER JOIN projects ON reviews.project_id = projects.id WHERE reviews.type='comment' AND reviews.user_id=#{params[:id].to_i}")
    @is_following = (ActiveRecord::Base.connection.execute("SELECT * FROM followers WHERE following_id=#{params[:id].to_i} AND follower_id=#{current_user['id'].to_i}") || []).count >= 1
  end

  def backed
    @user = User.find(params[:id].to_i)
    @projects = ActiveRecord::Base.connection.execute("SELECT * FROM projects WHERE id IN (SELECT projects.id FROM projects INNER JOIN pledges ON projects.id = pledges.project_id WHERE pledges.user_id=#{params[:id]})").to_a
    @projects.each do |project|
      ar_project = Project.find(project['id'].to_i)
      unless ar_project.project_image_file_name.nil?
        project['project_image_url'] = ar_project.project_image.url
      end
    end
    @comments = ActiveRecord::Base.connection.execute("SELECT projects.title, reviews.comment, reviews.created_at FROM reviews INNER JOIN projects ON reviews.project_id = projects.id WHERE reviews.type='comment' AND reviews.user_id=#{params[:id].to_i}")
    @is_following = (ActiveRecord::Base.connection.execute("SELECT * FROM followers WHERE following_id=#{params[:id].to_i} AND follower_id=#{current_user['id'].to_i}") || []).count >= 1
  end

  def comments
    @user = User.find(params[:id].to_i)
    @projects = ActiveRecord::Base.connection.execute("SELECT * FROM projects WHERE id IN (SELECT projects.id FROM projects INNER JOIN pledges ON projects.id = pledges.project_id WHERE pledges.user_id=#{params[:id]})")
    @comments = ActiveRecord::Base.connection.execute("SELECT projects.title, reviews.comment, reviews.created_at FROM reviews INNER JOIN projects ON reviews.project_id = projects.id WHERE reviews.type='comment' AND reviews.user_id=#{params['id'].to_i}")
    @is_following = (ActiveRecord::Base.connection.execute("SELECT * FROM followers WHERE following_id=#{params[:id].to_i} AND follower_id=#{current_user['id'].to_i}") || []).count >= 1
  end

  def credit_cards
    @credit_cards = ActiveRecord::Base.connection.execute("SELECT * FROM credit_cards where user_id = #{current_user['id'].to_i}")
  end

  def follow
    follower_id = current_user['id'].to_i
    to_be_followed = params[:id].to_i
    count = ActiveRecord::Base.connection.execute("SELECT * FROM followers WHERE following_id=#{to_be_followed} AND follower_id=#{follower_id}").count
    if count < 1
      ActiveRecord::Base.connection.execute("INSERT INTO followers (follower_id, following_id, created_at, updated_at) VALUES (#{follower_id}, #{to_be_followed}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)")
    end
    redirect_to :back
  end

  def unfollow
    follower_id = current_user['id'].to_i

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/about.html.erb
<!DOCTYPE html>
<html class="users_profile_about fontface js" data-request-id="2adcee6b-713b-4ba3-b119-8469419c0018" lang="en">
   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# kickstarter: http://ogp.me/ns/fb/kickstarter#">
   </head>
   <body class="profile users not-mobile not-phone not-mobile-safari not-chrome-ios not-forces-video-controls not-tablet not-ipad not-iphone not-ios not-android not-touchable not-native-app-request not-apple-pay-capable not-android-pay-capable responsive skip_autologin" id="users_profile_about">
      <div class="NS_layouts__notifications"></div>
      <%= render 'header' %>
      <%= render 'user_menu' %>
      <div id="start-of-content" tabindex="-1"></div>
      <main role="main">
         <div id="growl_section" class="center jGrowl"></div>
         <div id="main_content">
            <div class="z2" id="hover_label"></div>
            <%= render 'user_profile', locals: {backed_count: @projects.count, user: @user, is_following: @is_following} %>
            <div class="container-flex mobile-scroll-container px3">
               <div class="row mobile-scroll-row">
                  <div class="col col-12">
                     <div class="nav--subnav js-nav--subnav nav--subnav--center nav--subnav--short">
                        <div class="js-nav--subnav__selected-indicator nav--subnav__selected-indicator" style="left: 353.734px; width: 60px;"></div>
                        <ul class="nav--subnav__list">
                           <li class="nav--subnav__item">
                              <div class="nav--subnav__item__link nav--subnav__item__link--gray js-about-link current">About
                              </div>
                           </li>
                           <li class="nav--subnav__item">
                              <a class="nav--subnav__item__link nav--subnav__item__link--gray  js-backed-link" href="/users/<%= params[:id] %>/profile/backed">Backed
                              <span class="count">
                              <%= @projects.count %>
                              </span>
                              </a>
                           </li>
                           <li class="nav--subnav__item">
                              <a class="nav--subnav__item__link nav--subnav__item__link--gray  js-comments-link" href="/users/<%= params[:id] %>/profile/comments">Comments
                              <span class="count">
                              <%= @comments.count %>
                              </span>
                              </a>
                           </li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
            <div class="border-top" id="content-wrap">
               <div class="grid-container pb5 mt5" id="content">
                  <div class="grid-row">
                     <div class="col-full col-sm-20-24 col-md-16-24 col-center">
                        <div class="grid-row pt3">
                           <div class="col-full col-sm-5-20 col-md-5-16">
                              <h5 class="navy-500 f5">
                                 Biography
                              </h5>
                           </div>
                           <div class="col-full col-sm-15-20 col-md-11-16">
                              <p class="mb3 navy-600"></p>
                              <p><%= @user['biography'] %></p>
                              <p></p>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </main>

      <%= render 'svg' %>
   </body>
</html>

app/views/user/account.html.erb
<!DOCTYPE html>
<html class="users_edit fontface js" data-request-id="8bf20d5f-f0c7-4e55-be53-e637a5ae4e7f" lang="en">
   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# kickstarter: http://ogp.me/ns/fb/kickstarter#">

   </head>
   <body class="users_edit users not-mobile not-phone not-mobile-safari not-chrome-ios not-forces-video-controls not-tablet not-ipad not-iphone not-ios not-android not-touchable not-native-app-request not-apple-pay-capable not-android-pay-capable responsive skip_autologin" id="users_edit_account">
      <div class="NS_layouts__notifications"></div>
      <%= render 'header' %>
      <%= render 'user_menu' %>
      <div id="start-of-content" tabindex="-1"></div>
      <main role="main">
         <div id="growl_section" class="center jGrowl"></div>
         <div id="main_content">
            <section class="px3 mb3 bg-white border-bottom">
               <div class="container-flex px3 pt3 pt10-sm mobile-scroll-container">
                  <h1>Settings</h1>
                  <div class="nav--subnav js-nav--subnav mobile-scroll-row">
                     <div class="js-nav--subnav__selected-indicator nav--subnav__selected-indicator--blue" style="left: 0px; width: 56px;"></div>
                     <ul class="nav--subnav__list">
                        <li class="nav--subnav__item">
                           <div class="nav--subnav__item__link nav--subnav__item__link--gray current">Account</div>
                        </li>
                        <li class="nav--subnav__item"><a class="nav--subnav__item__link nav--subnav__item__link--gray" href="/users/<%= params[:id] %>/profile">Edit profile</a></li>
                        <li class="nav--subnav__item"><a class="nav--subnav__item__link nav--subnav__item__link--gray" href="/users/<%= params[:id] %>/credit_cards">Payment methods</a></li>
                        <li class="nav--subnav__item">
                           <a class="nav--subnav__item__link nav--subnav__item__link--gray" href="/users/<%= params[:id] %>/following">Following</a>
                        </li>
                     </ul>
                  </div>
               </div>
            </section>
            <div class="container-flex px3">
               <div class="row">
                 <% if notice %>
                   <div style="text-align: center; font-weight: bold; padding-bottom: 0px" class="btn btn--green btn--block submit">
                     <p>User created successfully!</p>
                     <p>Login to EXPLORE</p>
                   </div>
                  <% end %>
                  <% if alert %>
                    <div style="color: red; font-weight: bold" class="jGrowl-message">
                      <p>The email address and password you entered do not match.</p>
                    </div>
                  <% end %>
                  <div class="col col-5 col-post-1">
                    <%= form_tag password_reset_path, class: 'form-simple form-stacked', role: 'form', "accept-charset"=> "UTF-8", method: :post do %>
                        <fieldset class="mb3 mb10-sm">
                           <ol class="f5">
                              <li class="py2">
                                 <label class="bold" for="user_email">Email</label>
                                 <%= text_field_tag :email, '', class: 'input-text full-width text', value: @user['email'], style: 'width: 100%', type: 'text', placeholder: 'Enter an email address', id: 'user-email' %>
                              </li>
                              <li class="change_password py2 js-hide" style="display: list-item;">
                                 <label class="bold">New Password</label>
                                 <%= text_field_tag :password, '', class: 'input-text full-width js-auto_focus fs-hide password', type: 'password', placeholder: 'Password' %>
                                 <span class="grey-dark">Minimum 6 characters</span>
                              </li>
                              <li class="change_password py2 js-hide" style="display: list-item;">
                                 <label class="bold">Confirm Password</label>
                                 <%= text_field_tag :confirm_password, '', class: 'input-text full-width js-auto_focus fs-hide password', type: 'password', placeholder: 'Password' %>
                                 <span class="grey-dark">Make sure they match!</span>
                              </li>
                              <li class="current_password py2">
                                 <label class="bold">Current Password</label>
                                 <%= text_field_tag :current_password, '', class: 'input-text full-width js-auto_focus fs-hide password', type: 'password', placeholder: 'Password' %>
                                 <span class="grey-dark">
                                 Enter your current password to save these changes.
                                 </span>
                              </li>
                           </ol>
                           <div class="form-submit">
                              <input type="submit" name="commit" value="Reset password" class="btn btn--blue submit">
                           </div>
                        </fieldset>
                     <% end %>
                  </div>
               </div>
            </div>
         </div>
      </main>

      <%= render 'svg' %>
   </body>
</html>

app/views/user/profile.html.erb
<!DOCTYPE html>
<html class="users_edit fontface js" data-request-id="7830c0e3-1bc8-44d8-99ee-4834070e43c9" lang="en">
   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# kickstarter: http://ogp.me/ns/fb/kickstarter#">

   </head>
   <body class="users_edit users not-mobile not-phone not-mobile-safari not-chrome-ios not-forces-video-controls not-tablet not-ipad not-iphone not-ios not-android not-touchable not-native-app-request not-apple-pay-capable not-android-pay-capable responsive skip_autologin" id="users_edit_profile">
      <div class="NS_layouts__notifications"></div>
      <%= render 'header' %>
      <%= render 'user_menu' %>
      <div id="start-of-content" tabindex="-1"></div>
      <main role="main">
         <div id="growl_section" class="center jGrowl"></div>
         <div id="main_content">
            <section class="px3 mb3 bg-white border-bottom">
               <div class="container-flex px3 pt3 pt10-sm mobile-scroll-container">
                  <h1>Settings</h1>
                  <div class="nav--subnav js-nav--subnav mobile-scroll-row">
                     <div class="js-nav--subnav__selected-indicator nav--subnav__selected-indicator--blue" style="left: 99.6406px; width: 72px;"></div>
                     <ul class="nav--subnav__list">
                        <li class="nav--subnav__item">
                           <a class="nav--subnav__item__link nav--subnav__item__link--gray" href="/users/<%= params[:id] %>/account">Account</a>
                        </li>
                        <li class="nav--subnav__item"><div class="nav--subnav__item__link nav--subnav__item__link--gray current">Edit profile</div></li>
                        <li class="nav--subnav__item"><a class="nav--subnav__item__link nav--subnav__item__link--gray" href="/users/<%= params[:id] %>/credit_cards">Payment methods</a></li>
                        <li class="nav--subnav__item">
                           <a class="nav--subnav__item__link nav--subnav__item__link--gray" href="/users/<%= params[:id] %>/following">Following</a>
                        </li>
                     </ul>
                  </div>
               </div>
            </section>
            <div class="container-flex px3">
              <%= form_tag profile_update_path, class: 'form-simple', role: 'form', "accept-charset"=> "UTF-8", multipart: true, method: :post do %>
                  <div class="row">
                     <fieldset class="col col-5 col-post-1">
                        <ol class="f5">
                           <li class="py2">
                              <label class="bold" for="user_name">Username</label>
                              <%= text_field_tag :username, '', class: 'required text', value: @user['username'], style: 'width: 100%', type: 'text', placeholder: 'Enter a unique name', id: 'user-name' %>
                           </li>
                           <li class="py2">
                              <label class="bold" for="user_name">Existing Photo (don't like it? Upload a new one)</label>
                              <img alt="Profile image" class="project-thumbnail-img" src=<%= @user.profile_image.url || @user.profile_image_url %> width="100%">
                           </li>
                           <li class="py2">
                              <label class="bold" for="user_Picture">Picture</label>
                              <div class="js-asset-upload asset_upload profile-photo avatar">
                                 <div class="upload">
                                   <%= file_field_tag :profile_image, class: 'photo file', class: 'avatar file', id: 'profile_photo' %>
                                    <strong class="center profile-photo">
                                    Choose an image from your computer
                                    </strong>
                                    <div class="progress">
                                       <div class="inner">
                                          <div class="bar">
                                             <div class="percentage">
                                                0%
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                              <span class="grey-dark">
                              JPEG, PNG, GIF, or BMP  •  50MB file limit
                              </span>
                              <div style="text-align: center; margin-top: 5px; margin-bottom: 5px">
                                OR
                              </div>
                              <div class="character_counter_wrapper">
                                <%= text_field_tag :profile_image_url, '', class: 'required text', value: @user['profile_image_url'], style: 'width: 100%', type: 'text', placeholder: 'Enter a public URL for the image', id: 'user-profile-image' %>
                              </div>
                           </li>
                           <li class="py2">
                              <label class="bold" for="user_biography">Biography</label>
                              <%= text_area_tag :biography, @user['biography'], style: 'height: 100px', class: 'input-textarea textarea', type: 'text', placeholder: 'Need not write a book, just introduce yourself', id: 'user_biography' %>
                              <span class="grey-dark">We suggest a short bio. If it's 300 characters or less it'll look great on your profile.</span>
                           </li>
                        </ol>
                     </fieldset>
                     <fieldset class="col col-6">
                        <ol class="f5">
                          <div style="display: flex; justify-content: space-between">
                            <li style="width: 40%" class="shortcut-url py2">
                               <label class="bold" for="user_slug">First name</label>
                               <%= text_field_tag :first_name, '', class: 'input-text input-search full-width text', value: @user['first_name'], style: 'width: 100%; padding-left: 10px', type: 'text', placeholder: 'Luke', id: 'user-email' %>
                            </li>
                            <li style="width: 40%" class="shortcut-url py2">
                               <label class="bold" for="user_slug">Last name</label>
                               <%= text_field_tag :last_name, '', class: 'input-text input-search full-width text', value: @user['last_name'], style: 'width: 100%; padding-left: 10px', type: 'text', placeholder: 'Skywalker', id: 'user-address' %>
                            </li>
                          </div>
                           <li class="shortcut-url py2">
                              <label class="bold" for="user_slug">Address</label>
                              <%= text_field_tag :address, '', class: 'input-text input-search full-width text', value: @user['address'], style: 'width: 100%; padding-left: 10px', type: 'text', placeholder: '373 92nd Street Apt A3', id: 'user-address' %>
                           </li>
                           <li class="shortcut-url py2">
                              <label class="bold" for="user_slug">State</label>
                              <%= text_field_tag :state, '', class: 'input-text input-search full-width text', style: 'width: 100%', value: @user['state'], type: 'text', placeholder: 'Eg: New York', id: 'user-state' %>
                           </li>
                           <li class="shortcut-url py2">
                              <label class="bold" for="user_slug">Country</label>
                              <%= text_field_tag :country, '', class: 'input-text input-search full-width text', style: 'width: 100%', value: @user['country'], type: 'text', placeholder: 'Eg: USA', id: 'user-country' %>
                           </li>
                           <li class="shortcut-url py2">
                              <label class="bold" for="user_slug">PIN</label>
                              <%= text_field_tag :pincode, '', class: 'input-text input-search full-width text', style: 'width: 100%', value: @user['pincode'], type: 'text', placeholder: 'Eg: USA', id: 'user-pincode' %>
                           </li>
                        </ol>
                     </fieldset>
                  </div>
                  <hr>
                  <div class="form-submit mb3 mb10-sm">
                     <input type="submit" name="commit" value="Save settings" class="btn btn--blue submit">
                  </div>
               <% end %>
            </div>
         </div>
      </main>

      <%= render 'svg' %>
   </body>
</html>